name: dry
version: latest 
version-script: cat APPVERSION
summary: A Docker manager for the terminal
description: |
  Dry is a terminal application to manage Docker. It can manage Containers, Images and Networks, and, if running a Docker Swarm, it can manage a Swarm cluster. It can be used with both local and remote Docker daemons.

grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.10.3
  dry:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/moncho/dry

apps:
  dry:
    command: dry
